from lib import *
from config import url_database_pyodbc

url_database_pyodbc = url_database_pyodbc

MST_TPNS = 9514

FOLDER_NHAP = os.path.join(os.path.dirname(__file__), r'nhapxuat/nhap')
FOLDER_XUAT = os.path.join(os.path.dirname(__file__), r'nhapxuat/xuat')
FOLDER_BIENBAN = os.path.join(os.path.dirname(__file__), r'nhapxuat/bienban')
FOLDER_JD = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/jd')
FOLDER_CV = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/cv')
FOLDER_DGPV = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/dgpv')

HINHANH_LOGO = os.path.join(os.path.dirname(__file__), r'static/img/logo.png')
FILE_MAU_HDTV_NT1_O2_TROLEN = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/o2_trolen/hdtv.xlsx')
FILE_MAU_HDTV_NT1_DUOI_O2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/duoi_o2/hdtv.xlsx')
FILE_MAU_HDCTH_NT1_O2_TROLEN = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/o2_trolen/hdcth.xlsx')
FILE_MAU_HDCTH_NT1_DUOI_O2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/duoi_o2/hdcth.xlsx')
FILE_MAU_HDVTH_NT1_O2_TROLEN = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/o2_trolen/hdvth.xlsx')
FILE_MAU_HDVTH_NT1_DUOI_O2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/duoi_o2/hdvth.xlsx')
FILE_MAU_HDNH_NT1_O2_TROLEN = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/o2_trolen/hdnh.xlsx')
FILE_MAU_HDNH_NT1_DUOI_O2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt1/duoi_o2/hdnh.xlsx')
FILE_MAU_HDTV_NT2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt2/hdtv.xlsx')
FILE_MAU_HDCTH_NT2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt2/hdcth.xlsx')
FILE_MAU_HDVTH_NT2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt2/hdvth.xlsx')
FILE_MAU_HDNH_NT2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/hopdong/nt2/hdnh.xlsx')
FILE_MAU_CDHD_NT1 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/chamduthopdong/nt1/cdhd.xlsx')
FILE_MAU_CDHD_NT2 = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/chamduthopdong/nt2/cdhd.xlsx')
FILE_MAU_DANGKY_TANGCA_NHOM = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/tangca/tangcanhom.xlsx') 
FILE_MAU_DANGKY_DOICA_NHOM = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/doica/doicanhom.xlsx') 
FILE_MAU_DANGKY_XINNGHIKHAC = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/xinnghikhac/xinnghikhac.xlsx') 
FILE_MAU_DANGKY_KPI = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/kpi/Kpi report sample.xlsx') 
FILE_MAU_CAPNHAT_STK = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/capnhatstk/capnhatstk.xlsx')
FILE_MAU_THEM_HOPDONG = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/nhaphophong/taohopdong.xlsx')
FILE_MAU_DIEU_CHUYEN = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/dieuchuyen/dieuchuyen.xlsx')
FILE_MAU_BANGCONG_HANHCHINH = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_hanhchinh.xlsx')
FILE_MAU_BANGCONG_TONGHOP = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_tonghop.xlsx')
FILE_MAU_BANGCONG_CHUACHOT = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chuachot.xlsx')
FILE_MAU_BANGCONG_CHUNHAT_CHUACHOT = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chunhat_chuachot.xlsx')
FILE_MAU_BANGCONG_CHOT = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chot.xlsx')
FILE_MAU_BANGCONG_CHUNHAT_CHOT = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chunhat_chot.xlsx')
FILE_MAU_BANGCONG_TRANGOAI = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_trangoai.xlsx')
FILE_MAU_BANGCONG_HANHCHINH_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_hanhchinh_kx.xlsx')
FILE_MAU_BANGCONG_TONGHOP_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_tonghop_kx.xlsx')
FILE_MAU_BANGCONG_CHUACHOT_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chuachot_kx.xlsx')
FILE_MAU_BANGCONG_CHUNHAT_CHUACHOT_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chunhat_chuachot_kx.xlsx')
FILE_MAU_BANGCONG_CHOT_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chot_kx.xlsx')
FILE_MAU_BANGCONG_CHUNHAT_CHOT_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/bangcong/mau_bangchamcong_chitiet_chunhat_chot_kx.xlsx')
FILE_MAU_LAMTHEMGIO_CHEDO = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_chedo.xlsx')
FILE_MAU_LAMTHEMGIO_BANNGAY = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_banngay.xlsx')
FILE_MAU_LAMTHEMGIO_BANDEM = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_bandem.xlsx')
FILE_MAU_LAMTHEMGIO_CHUNHAT = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_chunhat.xlsx')
FILE_MAU_LAMTHEMGIO_NGAYLE = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_ngayle.xlsx')
FILE_MAU_LAMTHEMGIO_CHEDO_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_chedo_kx.xlsx')
FILE_MAU_LAMTHEMGIO_BANNGAY_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_banngay_kx.xlsx')
FILE_MAU_LAMTHEMGIO_BANDEM_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_bandem_kx.xlsx')
FILE_MAU_LAMTHEMGIO_CHUNHAT_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_chunhat_kx.xlsx')
FILE_MAU_LAMTHEMGIO_NGAYLE_KX = os.path.join(os.path.dirname(__file__), r'static/uploads/mau/lamthemgio/mau_lamthemgio_ngayle_kx.xlsx')